### ISSUE TITLE
Issue generating the Lorem Ipsum after removing and reinstalling

### ISSUE THREAD

**Issue by Tes3awy** [lkcampbell/brackets-lorem-ipsum#12]
I have installed your extension in Brackets on a Windows 10 machine, and it worked well at first. Then I accidentally removed it. When I installed in again, it doesn't work at all. When I press ctrl+shift+L as it's the default shortcut. It removes the text before the location where the cursor is. Any idea why this is happening ? 

for example if there is a paragraph tag that I want to insert the lorem ipsum in between. When I press ctrl+shift+L it becomes only the closing tag.

**Comment by MarHaj** [comment]
#12 The same happened to me.
So I have included a new record into keymap.json (overriding of key bindings):
`"Ctrl-Shift-L": "lkcampbell.loremIpsum"`
and it works again like a charm.

**Comment by lkcampbell** [comment]
@Tes3awy Not sure, maybe the keymap combo is assigned to another command? Keymaps are assigned on a first come first serve basis so something else might be assigned to the keymap before Lorem Ipsum can get it.

Try installing the Display Shortcuts extension and look up the keymap assignment and let me know what it is.

**Comment by Tes3awy** [comment]
@lkcampbell I installed the Display Shortcuts extension as you mentioned. It's pretty useful by the way. But I didn't find that CTRL+SHIFT+L is assigned to any command. Only CTRL+L and CTRL+ALT+L are assigned to select line, and split selections into lines respectively.

**Comment by lkcampbell** [comment]
@Tes3awy, that's weird. Okay, I have access to a Windows 10 machine with Brackets on it at work. I will test it there and see if I can reproduce the issue. Are you just hitting the combo with no lorem command or are you entering a lorem command first?

**Comment by lkcampbell** [comment]
@Tes3awy never mind, I reproduced the problem on my Mac, I will take a look at it, thanks.

**Comment by lkcampbell** [comment]
@Tes3awy to confirm, you are simple using the shortcut key and not entering any string before it like "lorem" or lorem_3s_long" or anything like that, correct?

And it is making exactly seven characters disappear?

**Comment by Tes3awy** [comment]
@lkcampbell Exactly

**Comment by lkcampbell** [comment]
Okay, I am fixing it now. It is a bug with the new `brackets-lorem-ipsum.onNoCommand` preference. For now, though you just need to type "lorem" first, then hit the shortcut key.

**Comment by lkcampbell** [comment]
Fixed in version 1.2.1.

@Tes3awy, if you want to use this extension without typing in a command first, you will need to set the `brackets-lorem-ipsum.onNoCommand` preference first. The default is "nothing", which does...well...nothing :).

Check out: https://github.com/lkcampbell/brackets-lorem-ipsum#extension-preferences.

It lists the different extension preferences and has a link to a Brackets wiki article on how to set preferences in general.

**Comment by Tes3awy** [comment]
@lkcampbell I have changed the line `"brackets-lorem-ipsum.onNoCommand": "nothing",` to `"brackets-lorem-ipsum.onNoCommand": "lorem",` in the defaultPreferences.json file. When I press CTRL+SHIFT+L the problem persists !. Am I doing something wrong ?

**Comment by lkcampbell** [comment]
@Tes3awy you shouldn't be changing anything in defaultPreferences.json. You should be changing brackets.json.

**Comment by lkcampbell** [comment]
And, of course, update the extension to the newest version.

**Comment by Tes3awy** [comment]
Thanks a lot @lkcampbell. Lorem Ipsum is one of my favorite extensions in Brackets btw.
